### PR TITLE
Remove ContextProviderValue type to allow proper interop

### PR DESCRIPTION
**Pull request by strican**
This solves #179 by changing the type of `DeckProps.ContextProvider` and removing a now unnecessary type.

### CODE REVIEW

**Comment by strican** [comment]
@danmarshall Can I get a review for this?

**Comment by danmarshall** [comment]
Hi @strican - can we pass the Context type in as a generic?
Perhaps something like 
```ts
export interface DeckProps<T=ContextProvider>
```

**Comment by strican** [comment]
> Hi @strican - can we pass the Context type in as a generic?
> Perhaps something like
> 
> ```ts
> export interface DeckProps<T=ContextProvider>
> ```

Kinda. If we provide that default value, it doesn't enable us to define a `ContextProvider` as described in the issue as JSX. If we wanted that, it needs to be propagated up to the `Deck` type, and then over to `DeckGLProps` and `DeckGL` in the react module. I'm not sure how much value that provides but I've done it.

**Comment by danmarshall** [comment]
I see. There is a strange syntax to support this, as described in [this article](https://mariusschulz.com/blog/passing-generics-to-jsx-elements-in-typescript):
```js
  return (
    <Select<string>
      options={targets}
      value={target}
      onChange={setTarget}
    />
  );
```
The article also says:
> Notice that we don't have to specify the generic type argument in the JSX element explicitly here. TypeScript can infer it for us!

Perhaps you can add a unit test to illustrate a custom `ContextProvider`?

**Comment by strican** [comment]
If I'm reading that article correctly, that's what I'm doing here. `Select` is still defined as generic, just as I'm doing for `DeckGL` here. The line you quoted just means the Typescript compiler infers the type from the attributes. i.e. they can type  `<Select ...>` instead of `<Select<string> ...>`. In this case, we can still just declare

```
<DeckGL 
 ContextProvider={MapContext.Provider}
>
```

normally, because it infers the `ContextProvider` type from the attribute.

**Comment by danmarshall** [comment]
Ok, when you said:
>  If we provide that default value, it doesn't enable us to define a ContextProvider as described in the issue as JSX
I thought you meant that this PR was not sufficient for the result you wanted to achieve. If you're happy with this PR, I'm happy with it.

**Comment by strican** [comment]
Sorry, what I meant by that was that alone wasn't sufficient, because we needed to propagate the parameter up to the `Deck` and `DeckGL` types. I did that but what I was saying was that I wasn't sure how much value that provided.

It sounds like we agree that this is the best we're getting for a parameterized solution, so I'm good with this.

**Comment by danmarshall** [comment]
Thanks! Published 4.8.0

**Pull request merged**
