### PR TITLE
added @luma.gl/shadertools

### PR DESCRIPTION
**Pull request by danmarshall**

### CODE REVIEW

**Comment by danmarshall** [comment]
@MGHawes can you try installing from this branch to test it out?

**Comment by MGHawes** [comment]
@danmarshall, sure - noob question, what's the best way of doing that?

**Comment by danmarshall** [comment]
in your `package.json`, change:
```js
"@danmarshall/deckgl-typings": "^3.1.0",
```
to:
```
"@danmarshall/deckgl-typings": "https://github.com/danmarshall/deckgl-typings.git#luma.gl/shadertools",
```

then `npm install`, then try compiling.

**Comment by MGHawes** [comment]
Trying now, running into a couple of issues but making sure they're not just my fault first

**Comment by MGHawes** [comment]
Okay, so I think I found the issue
image

Is there a reason that all of these methods on `DeckGL` were removed?
The error specifically is that you need to specify the props explicitly:
`React.Component<DeckProps, {}>`

**Comment by MGHawes** [comment]
It feels like we should at least have these:
https://deck.gl/#/documentation/submodule-api-reference/deckgl-react/deckgl?section=methods

**Comment by danmarshall** [comment]
We'll merge this to master and you can try from a new version...

**Comment by danmarshall** [comment]
@MGHawes published 3.2.0

**Pull request merged**
