### PR TITLE
Setup editorconfig, prettier and auto-format

### PR DESCRIPTION
**Pull request by wangxingkai**
I found we have quite a few inconsistent code styles in the codebase when I was making the previous changes.

so here I add the `editorconfig` and `prettier` to the repo. having them automatically do the code formatting for us.

the files changed in the first commit are the config files that I added.
the files changed in the second commit are all done by `prettier`.

I'm happy to adjust the configurations to satisfy any existing preference of the repo if we have one.

### CODE REVIEW

**Comment by danmarshall** [comment]
Thanks @wangxingkai ! Personally, I'm a VSCode user. I just use the built-in autoformat feature. Is there also a way you can tie into that? If you're not a VSCode user then disregard.

**Comment by wangxingkai** [comment]
Yea, I'm also a VSCode user. but I think people got different local default settings for their own VSCode (tab/space indent, indent size, single/double quote etc.). When I made the previous changes, I can't have my built-in autoformat on, otherwise, it will make a lot of format changes for the file I touched.

**Comment by danmarshall** [comment]
What if the Prettier VSCode extension is installed, will it use the `.prettierrc` file and 'just work'?

**Comment by wangxingkai** [comment]
yep, the VSCode extensions (Prettier, EditorConfig) will automatically recognise the setting files. then everyone's VSCode will automatically align with the same settings in the repo which are also used by the npm scripts.

**Comment by danmarshall** [comment]
Thanks!

**Pull request merged**
