### PR TITLE
reference to deck.gl/extensions (#214)

### PR DESCRIPTION
**Pull request by mdeljavan**
After installing any package, We encounter this error: can not resolve @deck.gl/extensions.

### CODE REVIEW

**Comment by danmarshall** [comment]
Thanks! The diff shows a lot of whitespace-only changes. Can you revert these and only add the needed ref at the top?

**Comment by mdeljavan** [comment]
I am so sorry. i reverted these and push again.

**Comment by danmarshall** [comment]
Great, thank you!

**Comment by danmarshall** [comment]
Published 4.9.7

**Pull request merged**
