### PR TITLE
initializeState takes a context as an arg

### PR DESCRIPTION
**Pull request by stevenroussey-privicy**
using any at the moment, will update whenever i figure out what it is. For now, this will help in creating sub-classes.

### CODE REVIEW

**Comment by stevenroussey-privicy** [comment]
Needed for Issue #110

**Comment by Pessimistress** [comment]
FYI the `context` object is defined here:

https://github.com/visgl/deck.gl/blob/master/modules/core/src/lib/layer-manager.js#L37-L53

and https://github.com/visgl/deck.gl/blob/master/modules/core/src/lib/layer-manager.js#L37-L53

The ones commonly used by the official layers (and likely any custom layers) are

- deck (`Deck`)
- gl (`WebGLContext`)
- viewport (`Viewport`)
- mousePosition (`[Number, Number]`)

**Comment by danmarshall** [comment]
@stevenroussey-privicy let me know when this is ready to merge.

**Comment by stevenroussey-privicy** [comment]
It’s ready

**Pull request merged**
