### PR TITLE
add unit to point radius in GeoJsonLayer

### PR DESCRIPTION
**Pull request by seed-of-apricot**

### CODE REVIEW

**Comment by seed-of-apricot** [comment]
Why has the spacing been changed...? The linter/prettier has never worked in my VSCode while I was editing.  
I will make it consistent with the original fine.

**Comment by seed-of-apricot** [comment]
Fixed. One space between `D` and `P` was found in another file so I think it's fine.

**Comment by danmarshall** [comment]
I usually go with the default formatting provided by VSCode. FWIW, I think the formatting was wrong previously and you fixed it 🤓. Thanks!

**Comment by danmarshall** [comment]
Published 4.3.5

**Pull request merged**
